-- Run this in the Supabase SQL editor for your project.
-- It creates public read access for the exercise library.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null references public.categories(name) on update cascade on delete restrict,
  sports text[] not null default '{}',
  equipment text[] not null default '{}',
  focus text not null default '',
  description text not null default '',
  coaching text not null default '',
  programming text not null default '',
  video_url text,
  video_path text,
  created_at timestamptz not null default now(),
  unique (name, category)
);

alter table public.categories enable row level security;
alter table public.exercises enable row level security;

drop policy if exists "Anyone can read categories" on public.categories;
create policy "Anyone can read categories"
on public.categories
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can read exercises" on public.exercises;
create policy "Anyone can read exercises"
on public.exercises
for select
to anon, authenticated
using (true);

-- Optional: allow signed-in coaches to manage the library from future admin screens.
-- Leave these policies disabled until you add Supabase Auth.
--
-- create policy "Signed-in users can add categories"
-- on public.categories for insert to authenticated
-- with check (true);
--
-- create policy "Signed-in users can update categories"
-- on public.categories for update to authenticated
-- using (true)
-- with check (true);
--
-- create policy "Signed-in users can add exercises"
-- on public.exercises for insert to authenticated
-- with check (true);
--
-- create policy "Signed-in users can update exercises"
-- on public.exercises for update to authenticated
-- using (true)
-- with check (true);

insert into public.categories (name, description, sort_order)
values
  ('Speed and Agility', 'Acceleration, deceleration, change of direction, and footwork quality.', 1),
  ('Strength', 'Force production and foundational tissue resilience.', 2),
  ('Power', 'Fast force expression through loaded or ballistic movements.', 3),
  ('Explosiveness', 'Rapid intent, reactive movement, and first-step pop.', 4),
  ('Endurance', 'Repeated effort capacity and conditioning support.', 5),
  ('Balance', 'Body control, stability, and position awareness.', 6)
on conflict (name) do update
set description = excluded.description,
    sort_order = excluded.sort_order;

-- For Supabase Storage videos:
-- 1. Create a public bucket named exercise-videos in Storage.
-- 2. Upload videos there.
-- 3. Put either the full public URL in exercises.video_url,
--    or the bucket path, such as speed/ladder-in-in-out-out.mov, in exercises.video_path.
